X-Project/Controllers/FriendsController.cs
using Facebook;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using X_Project.Attribute;
using X_Project.Extension;
using X_Project.ModelData;
using X_Project.Models;
using X_Project.Repository;
using X_Project.Services;

namespace X_Project.Controllers
{
    [RoutePrefix("friends")]
    [Authorize]
    [FacebookAccessToken]
    public class FriendsController : Controller
    {
        //private WishListContext _context;
        private IFacebookService _facebookService;
        private IWishRepository _iRepository;

        public FriendsController(IFacebookService facebookService,/* WishListContext context,*/ IWishRepository Irepository)
        {
            _iRepository = Irepository;
            //_context = context;
            _facebookService = facebookService;
        }

        // GET: Friends
        public async Task<ActionResult> Index()
        {
            var access_token = HttpContext.Items["access_token"].ToString();
            if (access_token != null)
            {
                try
                {
                    var appsecret_proof = access_token.GenerateAppSecretProof();
                    
                    var friendsList = await _facebookService.GetFriends(access_token, appsecret_proof);

                    return View(friendsList);
                }
                catch (Exception)
                {

                    throw;
                }

            }
            else
            {
                throw new HttpException(404, "Missing Access Token");
            }

        }
        
        public async Task<ActionResult> UserProfile(string userId)
        {
            var wishlists = await _iRepository.GetWishlistById(userId);

            return View(wishlists);
        }
    }
}

X-Project/Views/Friends/Index.cshtml
@model IEnumerable<X_Project.Models.FacebookFriendsModel>
@{
    ViewBag.Title = "Index";
}

@*<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-6">
                <input type="hidden" value="@item.Id" />
                <img src="@item.ImageUrl" />
                <h2>@item.Name</h2>
                <link href="" />
                <h2>@item.WishListCount</h2>
                @Html.ActionLink("Go", "UserProfile", new { userId = item.UserId })
            </div>
        }
    </div>
</div>*@
<div class="MyContainer">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="friends-div">
                <div class="col-lg-6">
                    <img src="@item.ImageUrl" class="friends-img">
                    <div class="profile-text">
                        <h1 class="profile-name">@item.Name</h1>
                        @if (item.WishListCount == 0)
	                    {
		                     <strong style="color:#d66565">Has not wishlist yet!</strong>
                        }
                        else
                        {
                            @Html.ActionLink("WISHLIST", "UserProfile", new { userId = item.UserId, @style = "color: green;" })
                        }

                    </div>
                </div>
            </div>
        }
    </div>
</div>

X-Project/Views/Friends/USerProfile.cshtml
@model IEnumerable<X_Project.ModelData.WishListItem>

@{
    ViewBag.Title = "USerProfile";
}
    <button style="display:inline; float:left" type="button" class="btn btn-primary" aria-label="Left Align" onclick="location.href='@Url.Action("Index", "Friends")'">
        <span style="display:inline;" class="glyphicon glyphicon-arrow-left" aria-hidden="true">Back</span>
    </button>
<div class="MyContainer">
    <div class="item-div">
        @*<a href="" class="glyphicon glyphicon-arrow-left">Go Back</a>*@
        <h1 style="font-family:fantasy; display:inline;">Wishlist</h1>
    </div>
</div>

<div class="MyContainer">
    @foreach (var item in Model.OrderByDescending(x => x.Time))
            {
        <div class="item-div">
            <div class="item ">
                <img src="@item.Image" alt="item" />
                <h2>@item.Title</h2>
                <a href=@item.WishUrl style="text-decoration: underline;">View item</a>
            </div>
        </div>
    }
</div>